# Generated by Django 5.2.5 on 2025-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_article_country_profile_articlecountry_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
