# Generated by Django 5.2.5 on 2025-09-07 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_country_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('places', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articles',
            },
        ),
        migrations.AlterField(
            model_name='articlecountry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.articulo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.articulo'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
