# Generated by Django 5.2.5 on 2025-09-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_country_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_date',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=[], upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='places',
            field=models.JSONField(default=list),
        ),
    ]
