# Generated by Django 5.2.5 on 2025-09-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_articulo_alter_articlecountry_article_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCountry',
        ),
    ]
